### PR TITLE
BigEndianStream enhancement and Service Installation

### PR DESCRIPTION
**Pull request by jonstelly**
- Add StreamRole enum.  Used to specify which end of the conversation the stream represents.  Player Position + Rotation packet has some fields that are flipped client->server vs server->client.  This will allow BigEndianStream to be used for communication as a client.
- Change to Service Installer to support need for adding -service parameter.
- Added -install and -uninstall command-line options to ChraftServer to simplify installation

### CODE REVIEW

**Comment by ementalo** [comment]
Why would we need to communicate as a client in the server? 

Read is Client -> Server
Write is Server -> Client

**Comment by jonstelly** [comment]
You might not.  But one of the projects I'd like to put together is a minecraft proxy that could be used as a layer between the client and any other server.  So for instance, a server admin could create a proxy in front of a standard world server.  The proxy could add additional features or / commands.  It could keep statistics or track player accomplishments.  Depending on the plugin interfaces you guys come up with, the proxy could even use those (or maybe just certain types).

Another project I'm looking at is creating some bots, so that would require communication as a client.

In general I think it would be nice to make the Chraft library usable as more than a server.  It would be nice to have one .NET library that provides core Minecraft functionality that could be used to build a world editor, client, etc...

Does that make sense?

**Comment by justinstenning** [comment]
I can see the benefit to doing the changes that make the library more useable in other scenarios, providing that the changes are minimal and do not add overhead.

**Comment by ementalo** [comment]
Yes, I agree, I suggest that we make another branch that these changes can go into before pushing into master straight away

**Pull request merged**
